FROM node:18 as build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

# Для продакшена используем nginx, а не http-server
FROM nginx:1.22-alpine
COPY --from=build /app/build /usr/share/nginx/html

# Стандартный порт Nginx — 80, не 8000
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]